class SqlData {

    public static transactionSQL: string = 
    `SELECT t.FORM_BARCODE, t.TRANSACTION_ID, cb.INCORPORATION_NUMBER, tst.TRANSACTION_STATUS_DESC, tdx.INPUT_DOCUMENT_ID
    FROM TRANSACTION t, CORPORATE_BODY cb, TRANSACTION_STATUS_TYPE tst, TRANSACTION_DOC_XML tdx
    WHERE t.CORPORATE_BODY_ID = cb.CORPORATE_BODY_ID AND t.TRANSACTION_ID = tdx.TRANSACTION_ID AND t.TRANSACTION_STATUS_TYPE_ID = tst.TRANSACTION_STATUS_TYPE_ID
    AND t.FORM_BARCODE = :barcode AND ROWNUM = 1`
    
}

export default SqlData;

